# Generated by Django 3.0.2 on 2020-03-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperature',
            name='value',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5),
            preserve_default=False,
        ),
    ]
