# Generated by Django 3.0.2 on 2020-04-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapi', '0002_temperature_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temperature',
            name='unit',
        ),
        migrations.AddField(
            model_name='temperature',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
