# Generated by Django 3.0.2 on 2020-04-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapi', '0003_auto_20200411_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageReferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('file_path', models.CharField(max_length=60)),
            ],
        ),
    ]
