# Generated by Django 3.0.2 on 2020-04-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapi', '0004_imagereferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagereferences',
            name='file_path',
        ),
        migrations.AddField(
            model_name='imagereferences',
            name='image',
            field=models.ImageField(default=None, upload_to='images/% Y/% m/% d/'),
            preserve_default=False,
        ),
    ]
