:toc:
:toclevels: 3
:toc-title: Inhaltsverzeichnis
:sectanchors:
:numbered:

toc::[]

= Entwicklerdokumentation
Autoren: Justin Schirdewahn

== Entwurfsdokumentation

=== Systemarchitektur
Mit Sequenzdiagramm und Softwaredoku alles per compodoc + pydoc

=== Bibliotheken/Frameworks

==== Frontend Frameworks
Angular 8

==== Frontend Bibliotheken
    "@angular-devkit/schematics": "^9.1.8",
    "@angular/animations": "^9.1.7",
    "@angular/cdk": "^9.2.4",
    "@angular/common": "^9.1.7",
    "@angular/compiler": "^9.1.7",
    "@angular/core": "^9.1.7",
    "@angular/forms": "^9.1.7",
    "@angular/material": "^9.2.4",
    "@angular/platform-browser": "^9.1.7",
    "@angular/platform-browser-dynamic": "^9.1.7",
    "@angular/router": "^9.1.7",
    "@auth0/angular-jwt": "^5.0.1",
    "@ngx-gallery/core": "^5.0.0-beta.0",
    "@ngx-gallery/gallerize": "^5.0.0-beta.0",
    "@ngx-gallery/lightbox": "^5.0.0-beta.0",
    "angular-bootstrap-md": "^9.3.0",
    "chart.js": "^2.9.3",
    "core-js": "^3.6.5",
    "hammerjs": "^2.0.8",
    "mdbootstrap": "^4.18.0",
    "ngx-gallery": "^5.10.0",
    "rxjs": "~6.5.5",
    "tslib": "^1.13.0",
    "zone.js": "~0.10.2"
    "@angular-devkit/build-angular": "^0.901.6",
    "@angular/cli": "^9.1.6",
    "@angular/compiler-cli": "^9.1.7",
    "@angular/language-service": "^9.1.7",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.12.41",
    "codelyzer": "^5.2.2",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "^5.0.9",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.5.4",
    "protractor": "^5.4.4",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.8.3"

==== Backend Frameworks
Django Version 3.0.5
djangorestframework Version 3.11.0
asgiref 3.2.7
pytz 2019.3
sqlparse 0.3.1

==== Backend Bibliotheken
import datetime
import glob
import json
import os
import time
import requests
import sys

=== Datenbankschema
@startuml 'entities' entity TEMPERATURE { * id INTERGER  —  * degrees DECIMAL(5,2) * measure_time TIMESTAMP * measurement_session_id INTERGER }

entity WIND { * id INTERGER  —  * direction DECIMAL(5,2) * speed DECIMAL(5,2) * measure_time TIMESTAMP * measurement_session_id INTERGER }

entity IMAGE { * id INTERGER  —  * image VARCHAR(256) * measure_time TIMESTAMP * measurement_session_id INTERGER } entity SOLAR_CELL { * id INTEGER  —  * current FLOAT * voltage FLOAT * measure_time TIMESTAMP * measurement_session_id INTERGER }

entity BATTERY { * id INTERGER  —  * current FLOAT * voltage FLOAT * temperature FLOAT * measure_time TIMESTAMP * measurement_session_id INTERGER }

entity MEASUREMENT_SESSION { * session_id INTERGER  —  * datavolume INTEGER * created TIMESTAMP (CURRENT_TIMESTAMP) }

entity CONFIGURATION { * id INTERGER  —  * measurement_intervall INTEGER * res_hight INTEGER * res_width INTEGER }

entity CONFIG_SESSION { * id INTERGER  —  * creator VARCHAR(256) * time TIMESTAMP * applied BOOLEAN }

entity ADMIN { * id INTERGER  —  * username VARCHAR(256) (unique) * password VARCHAR(256) }

'relationships' "MEASUREMENT_SESSION" "1"←-"" "IMAGE" "MEASUREMENT_SESSION" "1"←-"" "WIND" "MEASUREMENT_SESSION" "1"←-"" "TEMPERATURE" "BATTERY" ""-→"1" "MEASUREMENT_SESSION" "SOLAR_CELL" ""-→"1" "MEASUREMENT_SESSION" "CONFIGURATION" "1" — "1" "CONFIG_SESSION" "ADMIN" "1" ←- "" "CONFIG_SESSION"

@enduml

=== Schnittstellen
Wurden selber entwickelt 

=== Sequenzdiagramm

== Softwaredokumentation

=== Frontend
npm run compodoc

=== Backend
python -m pydoc -b