= Architecture Notebook "Wetterstation MFCR"
Philipp Barth <s78830@htw-dresden.de>; Vorname2 Nachname2 <email2@domain.org>; Vorname3 Nachname3 <email3@domain.org>
0.1, 01.11.2019 
:toc: 
:toc-title: Inhaltsverzeichnis
:sectnums:
// Platzhalter für weitere Dokumenten-Attribute 


== Zweck
Dieses Dokument beschreibt die Philosophie, Entscheidungen, Nebenbedingungen, Begründungen, wesentliche Elemente und andere übergreifende Aspekte des Systems, die Einfluss auf Entwurf und Implementierung haben.

//Hinweise: Bearbeiten Sie immer die Abschnitte 2-6 dieser Vorlage. Nachfolgende Abschnitte sind empfohlen,aber optional und sollten je nach Umfang der künftigen Wartungsarbeiten, Fähigkeiten des Entwicklungsteams und Bedeutung anderer architektureller Belange. 

//Anmerkung: Die Architektur legt wesentliche EINSCHRÄNKUNGEN für den Systementwurf fest und ist ein Schlüssel für die Erfüllung nicht-funktionaler Eigenschaften!

== Architekturziele und Philosophie
Hauptziel des Systems ist es ausgewählte Wetterdaten (Windstärke, Windrichtung, Böenhaftigkeit, Temperatur) mittels eines Raspberry Pi und diversen Sensoren zu sammeln, diese an einen Webserver zu übermitteln und schließlich auf der Website des http://www.mfc-rossendorf.de[MFC Rossendorf] darzustellen.


Das System lässt sich aus Achitektur-Sicht in drei Teilbereiche kapseln. Ein **Backend** und zwei **Clients**:


- **Datensammlung und -übertragung auf dem Raspberry Pi** (_client 1_)
****
Der Raspi sammelt durch das Auslesen von Sensoren zyklisch Daten. Diese werden auf dem Raspi lokal zwischengespeichert. (Umsetzung durch Auftraggeber).
Anschließend postet der Raspi diese an eine REST-API.
****

- **Webserver** (_backend_)
****
Der Webserver erhält zyklisch die Daten vom Raspi und speichert diese in einer Datenbank. Außerdem bietet er eine REST-API für den Raspi an, damit dieser seine Konfigurationsparameter ermitteln kann.
Zudem kommuniziert er mit dem Web-Frontend (_client 2_) über eine REST-API zur Übertragung der Wetterdaten.
**** 


- **Web-Frontend** (_client 2_)
****
Das Web-Frontend konsumiert über die REST-API die gespeicherten Wetterdaten.
Die Darstellung dieser Daten findet dann auf der Website des http://www.mfc-rossendorf.de[MFC Rossendorf] statt.
****



**Wesentliche Architekturziele:**

* Ressourcenschonendes Vorgehen aufgrund eingeschränkter Hardware der Wetterstation
** Die Datenakquise und anschließende Übertragung an den Server erfolgt wahrscheinlich auf einem **Raspberry Pi 4**. Zwar hat dieser mittlerweile genügend Leistung um diesen Punkt zu vernachlässigen, jedoch sollte der externe Akku nicht unnötig beansprucht werden, da das System autark auf dem Flugplatz des MFCR läuft. 
Zudem sind die Wetterdaten lokal zu speichern um sie bei evtl. Verbindungsabbruch später später übertragen zu können.
* Robustheit gegen mögliche Fehler
** Das System soll nach Fertigstellung auf dem Flugplatz des MFCR im Freien installiert werden, was den Wartungsvorgang deutlich erschwert. Fehlerfälle müssen demnach sorgfältig behandelt und ggf. geloggt werden.
* Gute Wartbarkeit und Erweiterbarkeit
** Den Auftraggebern soll die Möglichkeit gegeben werden zu einem späteren Zeitpunkt weitere Funktionalitäten hinzuzufügen (bspw. zusätzlicher Sensor). Dafür sollte das System mit möglichst geringem Aufwand erweiterbar sein.
** Um dies zu unterstützen und die Entwicklung zu vereinfachen sollte auf gängige Design-Patterns (Clean Code) und Dokumentation wertgelegt werden. 
* Performance und Aktualität
** Der User sollte bei der Abfrage der Daten auf der Website Anworten mit möglichst geringer Antwortzeit vom Backend erhalten. 


//Hinweise: Beschreiben Sie die Philosophie der Architektur, d.h. den zentralen Ansatz für ihre Architektur. Identifizieren Sie alle Aspekte, die die Philosophie beeinflussen, z.B. komplexe Auslieferung Aspekte, Anpassung von Altsystemen oder besondere Geschwindigkeitsanforderungen. Muss es besonders robust sein, um eine langfristige Wartung und Pflege zu ermöglichen?

//Formulieren Sie eine Reihe von Zielen, die die Architektur in ihrer Struktur un ihrem Verhalten erfüllen muss. Identifizieren Sie kritische Fragen, die von der Architektur adressiert werden müssen, z.B. besondere Hardware-Abhängigkeiten, die vom Rest des Systems isoliert werden sollten oder Sicherstellung der Funktionsfähigkeit unter besonderen Bedingungen (z.B. Offline-Nutzung).


== Annahmen und Abhängigkeiten
. eingeschränkte Ressourcen:
.. die Wetterstation soll autark laufen
* kein Anschluss ans Stromnetz, nur ein Akku mit Solarmodul -> möglichst stromsparendes Vorgehen
* Netzwerkanbindung über UMTS-Stick mit beschränktem Datenvolumen -> Datenvolumen darf nicht überschritten werden

. Nicht-funktionale Vorgaben der Auftraggeber:
.. Auftraggeber hätten Backend des Webserver gern in einer Skriptsprache
. Technische Abhängigkeiten vom Auftraggeber:
.. Hardware lagert während der Entwicklungszeit beim Kunden -> externer Zugang muss gegeben und am besten immer verfügbar sein
.. Gewisse Funktionalität des Systems v.a. auf Hardwareebene übernimmt Kunde selbst, wie z.B. Integration des externen Wake-up Timers, Stromquellenmanagement, sowie das Auslesen der Sensoren. Wir nutzen in diesen Fällen nur die gestellten Schnittstellen. 

. Vorasugegange Entscheidungen der Auftraggeber:
.. Hosting der Website wird extern betrieben von "jweiland.net"
* dort soll auch die zusätzliche SW laufen
* Zudem wird unser System dann in das aktuelle TYPO3 CMS eingebettet um es auf der Website darzustellen
** Auftraggeber wollten sich darum kümmern

. Unerfahrenheit des Teams:
.. keiner hat nennenswerte Erfahrungen mit den Webtechnologien die wir einsetzen werden
* HTML, CSS, JS, REST, php -> größerer Zeitaufwand da Einarbeitung notwendig


//[List the assumptions and dependencies that drive architectural decisions. This could include sensitive or critical areas, dependencies on legacy interfaces, the skill and experience of the team, the availability of important resources, and so forth]

== Architektur-relevante Anforderungen
//Fügen Sie eine Referenz / Link zu den Anforderungen ein, die implementiert werden müssen, um die Architektur zu erzeugen.
. <<sys-wide-reqs-usability, Systemweite Anforderungen an Benutzbarkeit>>
. <<sys-wide-reqs-reliability, Systemweite Anforderungen an Zuverlässigkeit>>
. <<sys-wide-reqs-performance, Systemweite Anforderungen an Performance>>
. <<sys-wide-reqs-supportability, Systemweite Anforderungen an Wartbarkeit>>
. <<sys-wide-reqs-constraints,Weitere Systemweite Anforderungen>>



== Entscheidungen, Nebenbedingungen und Begründungen 
//[List the decisions that have been made regarding architectural approaches and the constraints being placed on the way that the developers build the system. These will serve as guidelines for defining architecturally significant parts of the system. Justify each decision or constraint so that developers understand the importance of building the system according to the context created by those decisions and constraints. This may include a list of DOs and DON’Ts to guide the developers in building the system.] 

. Programmiersprache Python für den Raspi verwenden
** Aufgrund der einfachen Wartbarkeit und guten Handhabbarkeit der Skriptsprache wurde diese Einschränkung von den Auftraggebern vorgegeben. Aufgrund der Vielzahl an verfügbaren Bibliothekten, riesigen Community und der schnell erlernbaren Syntax eine sinvolle Wahl. 
. Programmiersprache python mit dem Django Rest Framework für Backend verwenden
** Einige Teammitglieder haben bereits Erfahrung mit python. Des Weiteren ist die Sprache relativ leicht zu erlernen. Das Django Rest Framework bietet zusätzlich ein ORM an.
** Alternativ wurde vom Auftraggeber php als Backend vorgeschlagen -> womit allerdings niemand im Team Erfahrung hat
. Angular als Frontend Framework, da Entwickler bereits Erfahrungen damit haben
. persistente Datenspeicherung in einer DB, um Daten langfristig zu sichern
** das DBMS wurde vom Azftraggeber ausgewählt (mySQL)
. Kommunikation zwischen Raspi und Webserver bzw. DB-Server erfolgt über eine Rest-Schnittstellen über HTTPS 

== Architekturmechanismen
https://www2.htw-dresden.de/~anke/openup/core.tech.common.extend_supp/guidances/concepts/arch_mechanism_2932DFB6.html[Doku "Concept: Architectural Mechanism"]
//[List the architectural mechanisms and describe the current state of each one. Initially, each mechanism may be only name and a brief description. They will evolve until the mechanism is a collaboration or pattern that can be directly applied to some aspect of the design.]

//Beispiele: relationales DBMS, Messaging-Dienste, Transaktionsserver, Webserver, Publish-Subscribe Mechanismus

//Beschreiben Sie den Zweck, Eigenschaften und Funktion der Architekturmechanismen.

. Webserver
** kommuniziert mit dem Client sowie dem DB-Server um Kontent auszuliefern

. DB-Server
.. mit REST-Schnittstelle
** für CRUD-Operationen
.. mit mySQL-DBMS zur Speicherung der Daten

. Ajax
* Kommunikation zwischen Client und Server zur dynamischen Erstellung der Website

. relationales DBMS
** in einer mySQL-DB werden die Sensordaten vom Webserver gespeichert und abgerufen


== Wesentliche Abstraktionen
//[List and briefly describe the key abstractions of the system. This should be a relatively short list of the critical concepts that define the system. The key abstractions will usually translate to the initial analysis classes and important patterns.]

== Schichten oder Architektur-Framework
//[Describe the architectural pattern that you will use or how the architecture will be consistent and uniform. This could be a simple reference to an existing or well-known architectural pattern, such as the Layer framework, a reference to a high-level model of the framework, or a description of how the major system components should be put together.]
* Client-Server Model:
** User und Raspi fungieren als Clients, die über eine REST-Schnittstelle mit dem Webserver kommuniziert (request and response via http)
* MVC-Pattern:
** durch Django-REST Framework gegeben
*** Model = Speicherung der Entitäten in der DB (mySQL-DB)
*** View = Darstellung der Daten im Webbrowser des User (HTML, CSS, JS bzw. Angular)
*** Controller = Implementierung der Logik der Anwendung. Er empfängt die Requests der Clients, verarbeitet diese und antwortet diesen.


== Architektursichten (Views)
//[Describe the architectural views that you will use to describe the software architecture. This illustrates the different perspectives that you will make available to review and to document architectural decisions.]

Folgende Sichten werden empfohlen:

=== Logische Sicht
//Beschreibt die Struktur und das Verhalten Systemteilen, die hohen Einfluss auf die Architektur haben. Dies kann die Paketstruktur, kritische Schnittstellen, wichtige Klassen und Subsysteme sowie die Beziehungen zwischen diesen Elementen enthalten. Zudem sollten die physische und logische Sicht persistenter Daten beschrieben werden, wenn es diesen Aspekt im System gibt. Dies ist ein hier dokumentierter Teilaspekt des Entwurfs.
==== Dataflow-Diagram



=== Physische Sicht (Betriebssicht)
//Beschreibt die physischen Knoten (Rechner) des Systems, der Prozesse, Threads und Komponenten, die in diesen Knoten ausgeführt werden. Diese Sicht wird nicht benötigt, wenn das System in einem einzelnen Prozess oder Thread ausgeführt wird.

=== Use cases
//Eine Liste oder ein Diagramm der Use Cases, die architektur-relevante Anforderungne enthalten.
