= Protokoll zum Treffen am 08.04.2020

== Allgemeines
=== Zeit
17.00 bis 18.15 Uhr

=== Teilnehmer
* **intern:**
* [x] Clemens
* [x] Alexander
* [x] Justin
* [x] Philipp
* [x] Josephin
* [ ] Agustin
* [x] Hannes

* **extern:**
Herr Professor Iwe
Herr Thomas Brenner

== Iterationsplan
Siehe GitHub-Repository: /project_docs/Iterationsplan_10.adoc

== Themen
- Python & Django sind ok, allerdings ist eine Skriptsprache mit ordentlichen Kommentaren Voraussetzung
- Raspberry ist wieder erreichbar
- config UND configsession als Sitzungseinstellungen f체r Datenbank (Nutzer und Sitzung den Einstellungen zurordnen)
- Configwerte nicht in eine einzelne Tabelle schreiben, sondern weitere Tabelle mit Configeintr채gen mit Verweis auf Tabelle mit Configart und Wert
- noch eine Spalte in Configtabellen (resultspalte), in der steht ob eine Einstellung geklappt hat
- Backend kommt auf gleiches Ger채t wie die DB

Was 체bernehmen die Auftraggeber?

- Eine Datei pro Sensor, die wir in Zeitabschnitten abfragen (liegen in einem def. Ordner, Textformat)
- Rapsberry im Wartungsmmodus (wir sollen nur Information geben, 
  dass sich der Raspberry nicht runter fahren soll)

