= Protokoll zum Treffen am 27.05.2020

== Allgemeines
=== Zeit
17.00 bis 18.10 Uhr

=== Teilnehmer
* **intern:**
* [x] Clemens
* [x] Alexander
* [x] Justin
* [x] Philipp
* [x] Josefin
* [x] Agustin
* [x] Hannes

* **extern:**
Herr Professor Iwe, Herr Brenner

== Iterationsplan
Siehe GitHub-Repository: /project_docs/Iterationsplan_13.adoc

== Themen
. Vorstellung der Ergebnisse (vor allem Front-End mit den Datengraphen)
. Klärung weiterer Fragen

== Ergebnisse
. Front-End
.. Die Art der Darstellung ist OK
.. Das Aussehen des Front-End muss noch überarbeitet (verschönert) werden, aber die Funktionalität passt
.. Luftbild des Flugplatzes für die Windrichtung wird noch gegeben
.. Für Windrichtung/-geschwindigkeit sind nur die letzten 3-4 Stunden interessant
.. Datenvolumen/Spannungsverbrauch soll im Admin-Panel in Tages-Intervallen dargestellt werden
. Back-End
.. Die Session ID sollte auf Anfrage vom Raspberry vom Datenbankserver generiert und dann dem Raspberry übergeben werden, so ist sichergestellt das Daten und Bild die gleiche ID bekommen
.. Für das Datenvolumen ist die Größe des Bildes ausreichend
. Sonstiges
.. Realdaten werden in den kommenden Tagen noch gegeben
.. Bilder könnten bei geringer Größe und nützlichem Inhalt (d.h. man erkannt auch etwas) auch bei Nacht verschickt werden 
.. Die Definition der Datenstruktur kann in einer XSD-Datei vorgenommen werden, welche uns zugeschickt wird
.. Das nächste Treffen mit dem Kunden ist am 27.05.2020 17 Uhr geplant