= Protokoll zum Treffen am 20.05.2020

== Allgemeines
=== Zeit
17.00 bis 18.30 Uhr

=== Teilnehmer
* **intern:**
* [x] Clemens
* [x] Alexander
* [x] Justin
* [x] Philipp
* [x] Josefin
* [] Agustin
* [x] Hannes

* **extern:**
Herr Professor Iwe, Herr Brenner

== Iterationsplan
Siehe GitHub-Repository: /project_docs/Iterationsplan_12.adoc

== Themen
. Vorstellung der Ergebnisse (vor allem Front-End mit den Datengraphen)
. Klärung weiterer Fragen

== Ergebnisse
. Front-End
.. Die Art der Darstellung ist OK
.. Die Darstellung der Windrichtung soll ähnlich der von "Windfinder" erfolgen (s. Website mfcR)
.. Admin-Bereich hat niedrige Priorität, sollte aber bald angegangen werden
.. Die Weiterentwicklung des Front-End wird vor allem von Alexander, Justin und Clemens übernommen
. Back-End
.. Die Eintragung und Abfrage der Werte ist in der groben Struktur (JSON) OK
.. Die Werte können auch über eine View dargestellt werden, was bedeutet dass die Daten welche zu einem Messpunkt gehören auch durch eine ID in der DB diesem zugeordnet werden können -> verschönert nur, daher niedrige Priorität
.. Daten wie der Ladezustand (bzw. Stromverbrauch) des Akkus und der Datenverbrauch (Internet) sollen mit geloggt und in der DB gespeichert werden, wobei uns die Struktur dieser Daten noch zugeschickt wird
.. Der Adminbereich sollte wie im Front-End auch im Back-End bald angegangen werden (z.B. Config-Tabelle erstellen)
. Sonstiges
.. Der momentane Projektstand/-verlauf wird vom Kunden für zufriedenstellend befunden
.. Das nächste Treffen mit dem Kunden ist am 27.05.2020 17 Uhr geplant