= Reflexion Clemens Kujus

=== Teamrolle: Projektmananger / Analyst

Meine Rolle im Projekt war primär die des Projektmanagers und nebenläufig die des Front-End 
Entwicklers. Im großen und ganzen habe ich hier gelernt, dass es doch recht unterschiedliche 
Auffassungen  von Teamarbeit gibt und es schwierig ist, den Aufwand im Team gleichmäßig zu 
verteilen. Außerdem ist es äußerst hilfreich, immer wieder von Teammitgliedern den aktuellen 
Status ihrer Arbeit zu erfragen und falls nötig mit Nachfragen nachzuhaken. Die Arbeit an einem 
realen Projekt hat auch dazu beigetragen, dass wir nicht wie in anderen Belegprojekten das Rad 
neu erfinden und alle die gleiche Aufgabe lösen, sondern dass es für mich auch sehr motivierend 
ist wenn die Software Aussicht hat am Ende tatsächlich im Realbetrieb zu landen und genutzt zu 
werden. Das es sich um ein komplexes reales Problem handelt hat bei mir auch dazu beigetragen, 
dass ich den Nutzen der Vorgehensweisen in der Softwareentwicklung besser verstanden habe und 
die Grenzen des Wasserfallmodells doch schnell erreicht sind. Des Weiteren habe festgestellt, 
dass der Nutzen den Aufwand sowohl bei der Protokollierung von Meetings, dem Verteilen von 
Aufgaben als auch technischen Skizzen, Kommentaren usw. deutlich überwiegt.

In meiner Arbeit als Front-End Entwickler habe ich viel über die Arbeit im Team mit Software zur 
Versionsverwaltung und die Programmierung im Web-Bereich gelernt. So habe ich z.B. die Nutzung 
kleiner Commits und Git-branches kennen und nutzen gelernt. Außerdem habe ich einen Einblick in 
die große Menge an vorhandenen Frameworks und Tools bekommen und gemerkt dass es gar nicht so 
einfach ist, eine Website nach den Vorstellungen des Kunden zu gestalten.

Besonders stolz bin ich zum einen darauf, dass wir am Ende des Projekts eine Software abgeben, 
die sehr gute Aussicht hat tatsächlich genutzt zu werden und den Nutzern letztendlich Freude 
bereiten soll. Zum anderen möchte ich die Leistung des Teams hervorheben, welches trotz 
Unterschiede im Arbeitsuafwand auch als Team agierte und als Ziel die fertige Software vor Augen 
hat.