= Hauptaktivitäten zusammengefasst

== Anforderungserhebung und -analyse
Autoren: Clemens Kujus

Die Anforderungserhebung und -analyse wurde während des Projektverlaufs durchgeführt. Die Anforderungen wurden am Projektanfang vor allem in Use-Cases festgehalten. In der Vision wurden im Gegensatz zu den Use-Cases keine Abläufe beschrieben, sondern die grundsätzlichen Anforderungen und Rahmenbedingungen festgehalten. In den systemwide requirements wurden systemweite Anforderungen an die Wetterstation-Software definiert.

== Entwurf
Autoren: Alexander Schoch

Im Zuge der Anforderungsanalyse wurden erste Entwürfe für das zu entwickelnde Sytem erstellt. Anfang Januar entwickelten Philipp Barth (Architekt), Justin Schirdewahn (Entwickler) und Alexander Schoch (Entwickler) erste Designs für eine potentielle Datenbank- und Systemarchitektur. Diese wurden als  Richtlinie für Prototypisierung verwendet, während der Entwicklung weiter verfeinert und mit neuen Anforderungen der Auftraggeber weiterentwickelt.


== Implementierung
Autoren: Alexander Schoch

Die Implementierung des Frontends und Backends begann Ende April. Die Entwicklung des Backends und der Skripte des Raspberry Pi's übernahm Philipp Barth. Das Frontend wurde zunächst von Alexander Schoch entwickelt und später von Clemens Kujus unterstützt.

Das Frontend wurde in drei Bereiche unterteilt- Graphen, Webcam und Admin-Bereich.

Der Graphenbereich wurde von Alexander Schoch ab dem 22.04. entwickelt und im Verlaufe des Projektes, mit den sich ändernden Anforderungen der Auftraggeber in der Funtkionalität erweitert.

Die Webcam wurde zunächst von Justin Schirdewahn begonnen ohne die Verwendung von weiteren Bibliotheken. Dies erwies sich als nicht sehr erfolgreich und nach einigen Prototypen unter der Verwendung verschiedener Bibliotheknen für die Gallerie erwies sich die "ngx-gallery" als eine Alternative. Diese wurde ab dem 29. Juni von Alexander Schoch implementiert.

Clemens Kujus implementierte ab Mitte Juni den Adminbereich und wurde bei Problemen von Alexander Schoch unterstützt.

Das gesamte Backend unterlag in der Implementierung Philipp Barths Verantwortung
//PHILIPP FRAGEN 

== Test
Autoren: Clemens Kujus

Die Rolle des Testers wurde erst von Hannes Fogut ausgeführt. Mitte Mai 2020 wurden die ersten dynamischen Tests implementiert, wobei es noch Probleme gab diese mit Django zusammen auszuführen. Als diese gelöst wurden, liefen die Tests problemlos. Angestrebt wurde ein concurrent testing. Die Testdokumentation wurde vom Tester selbst bearbeitet. Der Architekt Philipp Barth half dem Tester bei der Erstellung und Dokumentation der Tests. Die Tests sind vor allem Positivtests und dienen der Verifikation. Die Validierung der Zwischenergebnisse erfolgte durch die regelmäßigen Treffen mit den Kunden. Akzeptanztests, d.h. die Abnahmetests, werden in Absprache mit den Kunden ausgeführt, sobald die Software den von den Kunden gewünschten Anforderungen entspricht.

Statische Tests wurden nicht mit Tools ausgeführt, sondern manuell durch die Teammitglieder. Dies wurde unter anderem durch die Nutzung von Pull Requests ermöglicht, bei dem eine zweite Person den Quellcode und die veränderten Dateien einsehen konnte und somit früh festellen konnte ob offensichtliche Fehler oder Konventionsverstöße begangen wurden.

== Übergabe und Dokumentation
Autoren: Clemens Kujus

Die Übergabe der Software erfolgte am 31.07.2020 an den Kunden Herr Thomas Brenner im Rahmen 
eines Meetings und Iterationsabschlusses. Dazu wurde ihm der Zugang zum Git-Repository des 
Projekts gewährt, welches er sich mit dem Release "Übergabeversion v1.0" auf seinen Computer 
geladen hat. Diese Vorgehensweise der Übergabe geschah im Einverständnis mit den Kunden. 
Zusätzlich zu der Software im "src" Ordner hat der Projektmanager die Anwenderdokumentation und 
die Betriebsdokumentation an Herr Brenner und Herr Professor Iwe per Mail übergeben. Die 
Software wurde vom Kunden dankend angenommen. Im Rahmen der Übergabe wurden noch einmal alle 
Funktionalitäten per Bildschrimübertragung auf einem Computer eines Entwicklers vorgeführt und 
abgenommen. Abnahmetests erfolgen im beidseitigen Interesse erst mit der Vollendung der Software 
durch das Projektteam, welche über den eigentlichen Rahmen (Abgabetermin Software, 
Dokumentation) hinaus geht. Das Protokoll zum Treffen ist https://github.com/philippBa13/Wetterstation/blob/projectmanagement/project_docs/protocols/Treffen_31_07_2020.adoc[hier] zu finden.

Die Dokumentation erfolgte während der Entwicklung soweit möglich. Anwenderdokumentation und 
Betriebsdokumentation bei der Übergabe zum 31.07.2020 bezogen sich auf die Übergabeversion. Der 
Projektbericht, aktualisierte Anwenderdokumentation, aktualisierte Betriebsdokumentation und 
Entwicklerdokumentation wurden erst nach der Übergabe an den Kunden angefertigt. Die 
Testdokumentation entstand mit den ersten Testmöglichkeiten und wurde nach und nach erweitert.
