:toc:
:toclevels: 3
:toc-title: Inhaltsverzeichnis
:sectanchors:
:numbered:

toc::[]

= Entwicklerdokumentation
Autoren: Justin Schirdewahn, Alexander Schoch

== Entwurfsdokumentation

=== Bibliotheken/Frameworks

==== Frontend Frameworks

Wir haben uns bei der Frontendentwicklung für Angular 9 entschieden, weil Angular eine schöne Struktur und viele Funktionalitäten von sich aus mitbrachte. Es ist ein etabliertes Framework für die Frontendentwicklung. Dadurch standen uns viele Möglichkeiten der Informationsbeschaffung zum erlernen von Angular zur Verfügung. Des Weiteren war das Interesse und der Wunsch, Angular zu lernen, bei den Entwicklern vorhanden. +
Der Kunde war mit der Wahl von Angular zufrieden und so stand der Verwendung nichts mehr im Weg.

==== Frontend Bibliotheken

@auth0/angular-jwt Version 5.0.1, https://github.com/auth0/angular2-jwt +
angular-bootstrap-md Version 9.3.0, https://getbootstrap.com/docs/4.5/getting-started/introduction/ +
chart.js Version 2.9.3", https://www.chartjs.org/docs/latest/ +
core-js Version 3.6.5", https://github.com/zloirock/core-js/blob/master/README.md +
hammerjs Version 2.0.8", https://hammerjs.github.io/api/ +
ngx-gallery Version 5.10.0", https://openbase.io/js/ngx-gallery/documentation +
rxjs Version 6.5.5", https://rxjs.dev/guide/overview +
@types/node Version 12.12.41", https://openbase.io/js/@types/node/documentation +
codelyzer Version 5.2.2", http://codelyzer.com/rules/ +

==== Backend Frameworks
Django Version 3.0.5, +
djangorestframework Version 3.11.0, +
asgiref Version 3.2.7, +
pytz Version 2019.3, +
sqlparse Version 0.3.1

==== Backend Bibliotheken
datetime, https://docs.python.org/3/library/datetime.html +
glob, https://docs.python.org/3/library/glob.html +
json, https://docs.python.org/3/library/json.html +
os, https://docs.python.org/3/library/os.html +
time, https://docs.python.org/3/library/time.html +
requests, https://requests.readthedocs.io/de/latest/api.html +
sys, https://docs.python.org/3/library/sys.html +

=== Datenbankschema
@startuml 'entities' entity TEMPERATURE { * id INTERGER  —  * degrees DECIMAL(5,2) * measure_time TIMESTAMP * measurement_session_id INTERGER }

entity WIND { * id INTERGER  —  * direction DECIMAL(5,2) * speed DECIMAL(5,2) * measure_time TIMESTAMP * measurement_session_id INTERGER }

entity IMAGE { * id INTERGER  —  * image VARCHAR(256) * measure_time TIMESTAMP * measurement_session_id INTERGER } entity SOLAR_CELL { * id INTEGER  —  * current FLOAT * voltage FLOAT * measure_time TIMESTAMP * measurement_session_id INTERGER }

entity BATTERY { * id INTERGER  —  * current FLOAT * voltage FLOAT * temperature FLOAT * measure_time TIMESTAMP * measurement_session_id INTERGER }

entity MEASUREMENT_SESSION { * session_id INTERGER  —  * datavolume INTEGER * created TIMESTAMP (CURRENT_TIMESTAMP) }

entity CONFIGURATION { * id INTERGER  —  * measurement_intervall INTEGER * res_hight INTEGER * res_width INTEGER }

entity CONFIG_SESSION { * id INTERGER  —  * creator VARCHAR(256) * time TIMESTAMP * applied BOOLEAN }

entity ADMIN { * id INTERGER  —  * username VARCHAR(256) (unique) * password VARCHAR(256) }

'relationships' "MEASUREMENT_SESSION" "1"←-"" "IMAGE" "MEASUREMENT_SESSION" "1"←-"" "WIND" "MEASUREMENT_SESSION" "1"←-"" "TEMPERATURE" "BATTERY" ""-→"1" "MEASUREMENT_SESSION" "SOLAR_CELL" ""-→"1" "MEASUREMENT_SESSION" "CONFIGURATION" "1" — "1" "CONFIG_SESSION" "ADMIN" "1" ←- "" "CONFIG_SESSION"

@enduml

=== Schnittstellen
Die Restschnittstellen wurden mit dem Djangorestframework selber entwickelt.

== Softwaredokumentation

=== Frontend
npm run compodoc
HTML Export

=== Backend
python -m pydoc -b
HTML Export