= Projektergebnisse
Autoren: Clemens Kujus

== Ziel am Projektanfang
Das Ziel des Projektes war eine funktionstüchtige und in den regulären Betrieb eingebundene Wetterstation-Software, welche die von der Wetterstation gemessenen Werte/aufgezeichneten Bilder zyklisch an eine Datenbank auf einem Webserver sendet, diese dort speichert und dem User durch Zugriff vom Browser aus anzeigt. In einem durch Login geschützten Adminbereich soll der Administrator Informationen über den Systemzustand erhalten und den Raspberry in einen Wartungsmodus versetzen können. Messwerte sollen interpoliert, Bilder in einer Galerie und diese Daten allgemein mit Zeitraumauswahl dynamisch dargestellt werden.

== Zielerreichung

=== Was haben wir erreicht
Erreicht haben wir mit der Übergabeversion eine lauffähige Software, die Werte aus einer lokalen Datenbank ausliest und dem Nutzer auf einer Weboberfläche anzeigt. Dabei wurden für die Daten logisch sinnvolle Werte benutzt, wie z.B. Windrichtung nur von 0°-359°. Die Software kann alle geforderten Messwerte (Temperatur, Windgeschwindigkeit, Windrichtung) interpoliert, dynamisch und mit Zeitraumbezug anzeigen. Die Galerie zeigt die Bilder anforderungsgemäß an, d.h. das aktuellste Bild wird hervorgehoben als erstes angezeigt und die Bilder werden für jeden gesuchten Zeitraum (tagesgenau) angezeigt. Im Adminbereich kann der Administrator systemrelevante Informationen durch Graphen einsehen. Dabei sieht er durch eigene Auswahl  entweder Strom/Spannung von Raspi und Akku, Leistungsaufnahme des Raspi und Ladestrom des Akku. Dabei werden Leistungaufnahme und Ladestrom nur auf Grundlage von hart implementierten Beispielwerten angezeigt.

=== Was haben wir *nicht* erreicht
Nicht erreicht haben wir die Inbetriebnahme der Software. Das liegt daran, dass wir durch die stetigen neuen/geänderten Anforderungen uns immer wieder neu darauf konzentriert haben dass das Produkt übrehaupt den Anforderungen der Kunden entspricht. Das deployment wurde außerdem dadurch schwierig, dass der finale Ort der Software, d.h. der Webserver, uns erst kurz vor Abgabe der Übergabeversion durch den Kunden bekannt gemacht wurde. Wir haben diesen schon deutlich früher angefragt, aber die Kunden mussten selbst erst noch einen Webserver wählen.

Des Weiteren ist kein Wartungsmodus verfügbar. Die Notwendigkeit eines solchen Wartungsmodus fiel schlichtweg aus den Anforderungen heraus, da der Raspi entgegen der ursprünglichen Aufgabenstellung nicht einschläft sondern immer an ist.

Die Anzeige der Informationen über den Systemzustand ist schwierig zu bewerten, das die Kunden selbst erst mitten in der Implementierungsphase entschieden haben was da ungefähr alles möglich sein soll und diese Anforderungen final erst kurz vor Abgabe der Übergabeversion spezifiziert hat. Es sind also Systeminformationen vorhanden, welche allerdings nicht den finalen Anforderungen der Kunden entsprechen.