= Reflexion Josefin Hähne

=== Teamrolle: Analyst / Architekt

Ich übernahm seit Anfang des Projekts in Software Engineering I die Rolle des Analysten und als Backup des Architekten.  Zunächst viel es mir nicht ganz so leicht mich in die Rolle hineinzufinden, aber nach ein bisschen Zeit kam ich gut zurecht. Ich habe gelernt mit verschiedenen Tools, wie zum Beispiel mit GitHub, Visual Studio Code oder Visual Paradigm, umzugehen und zu arbeiten. Ich finde es sehr schön an einem realen Projekt mitgearbeitet zu haben, mit dem man anderen helfen kann und das auch eingesetzt wird, und so Erfahrungen zu sammeln. 

Es war eine Herausforderung immer neue Anforderungen zu erhalten, diese zu analysieren und mit in das Projekt einzubinden, sowie auch eine komplette Konzeptänderung. Anfangs war es angedacht, dass der Raspi zyklisch (aller einer Stunde) aufwacht neue Daten postet und sich danach wieder schlafen legt. Im Laufe des Projekts änderte sich dies und der Raspi sollte nun die ganze Zeit aktiv bleiben. Dies lag auch daran, dass parallel zu unserer Software auch erst die Wetterstation auf dem Modellflugplatz errichtet wurde. Durch immer neue Anforderungen war es auch gut, dass durch die Pandemie der Zeitraum für die Projektbearbeitung verlängert wurde und wir so auch mehr Zeit hatten alle Wünsche der Kunden so gut es geht umzusetzen.

Auch wurde es in SE II schwieriger Termine für Teammeetings zu finden, bei denen alle anwesend sein können. Gut war, dass wir zwar einen vorgegebenen Slot im Stundenplan hatten, der für die Projektbearbeitung vorgesehen war, jedoch hat das nicht immer bei allen gepasst. Manche mussten zu der Zeit arbeiten. Bei mir war mein Kind zu Hause, um welches ich mich kümmern musste und das beschäftigt werden wollte. Somit erschwerte die Situation auch meine Arbeitsumgebung.

Dennoch hat die Kommunikation unter den Teammitgliedern gut funktioniert. Wir halfen uns gegenseitig bei Fragen oder Problemen und diskutierten, wenn nötig, darüber. Auch bezüglich der Auftraggeber funktionierte die Kommunikation gut, auch wenn sie manchmal etwas länger brauchten, um auf Emails zu antworten oder uns Informationen zukommen zu lassen, auf die wir warteten um in dem Projekt weiter zu kommen.

Beim nächsten Projekt würde ich schon eher beginnen mich genauer mit dem Thema auseinander zu setzen und einzuarbeiten. Des Weiteren nicht immer alles zu bejahen, sondern auch mehr zu hinterfragen, beispielsweise wenn es auf Projektende zugeht und von Seiten der Auftraggeber immer wieder Änderungen und neue Anforderungen gibt. Das erschwert das Projekt gut abzuschließen und auch vorher ausreichend zu testen.

Zusammenfassend war es aber eine schöne Erfahrung bei diesem Projekt mitgewirkt zu haben, ich habe viel dadurch gelernt  und  konnte daraus auch viel mitnehmen, nicht nur in Bezug auf Software Engineering, sondern auch in einem solchen Softwareteam zu arbeiten. Man nimmt durch die praktische Anwendung mehr in das Berufsleben mit als hätte man nur die Techniken theoretisch gelehrt bekommen.
