= Reflexion Clemens Kujus

=== Teamrolle: Projektmananger / Analyst

Meine Rolle im Projekt war primär die des Projektmanagers und nebenläufig die des Front-End 
Entwicklers. Im großen und ganzen habe ich hier gelernt, dass es doch recht unterschiedliche 
Auffassungen  von Teamarbeit gibt und es schwierig ist, den Aufwand im Team gleichmäßig zu 
verteilen. Außerdem ist es äußerst hilfreich, immer wieder von Teammitgliedern den aktuellen 
Status ihrer Arbeit zu erfragen und falls nötig mit Nachfragen nachzuhaken. Die Arbeit an einem 
realen Projekt hat auch dazu beigetragen, dass wir nicht wie in anderen Belegprojekten das Rad 
neu erfinden und alle die gleiche Aufgabe lösen, sondern dass es für mich auch sehr motivierend 
ist wenn die Software Aussicht hat am Ende tatsächlich im Realbetrieb zu landen und genutzt zu 
werden. Das es sich um ein komplexes reales Problem handelt hat bei mir auch dazu beigetragen, 
dass ich den Nutzen der Vorgehensweisen in der Softwareentwicklung besser verstanden habe und 
die Grenzen des Wasserfallmodells doch schnell erreicht sind. Des Weiteren habe ich festgestellt, 
dass der Nutzen den Aufwand sowohl bei der Protokollierung von Meetings, dem Verteilen von 
Aufgaben als auch technischen Skizzen, Kommentaren usw. deutlich überwiegt.

In meiner Arbeit als Front-End Entwickler habe ich viel über die Arbeit im Team mit Software zur 
Versionsverwaltung und die Programmierung im Web-Bereich gelernt. So habe ich z.B. die Nutzung 
kleiner Commits und Git-branches kennen und nutzen gelernt. Außerdem habe ich einen Einblick in 
die große Menge an vorhandenen Frameworks und Tools bekommen und gemerkt dass es gar nicht so 
einfach ist, eine Website nach den Vorstellungen des Kunden zu gestalten.

Besonders stolz bin ich zum einen darauf, dass wir am Ende des Projekts eine Software abgeben, 
die sehr gute Aussicht hat tatsächlich genutzt zu werden und den Nutzern letztendlich Freude 
bereiten soll. Zum anderen möchte ich die Leistung des Teams hervorheben, welches trotz 
Unterschiede im Arbeitsaufwand auch als Team agierte und als Ziel die fertige Software vor Augen 
hat.

Gut funktioniert hat vor allem in der zweiten Projekthälfte die Kommunikation untereinander und 
mit den Kunden. Durch regelmäßige Onlinetreffen sowohl im gesamten Team (spätestens alle 2 
Wochen, oft wöchentlich) als auch in kleineren Kreisen, z.B. unter den Entwicklern, waren immer 
mehrere Beteiligte über den aktuellen Stand und akutelle Probleme informiert. Da ab Mai 2020 die 
Treffen fast immer wöchentlich mit den Kunden statt fanden, waren diese auch immer über Probleme 
und den aktuellen Stand informiert und konnten uns direkt Feedback geben. Die Kommunikation auf 
technischer Sicht war mit den Kunden aufgrund derer Fachexpertise in dem Bereich ebenfalls sehr 
angenehm. Gut funktioniert hat aus meiner Sicht des Projektmanagers vor allem die 
Implementierung. Mit Angular und Django haben die Entwickler meiner Meinung nach sehr gute 
Frameworks herausgesucht, mit welchen sie sehr schnell neue Funktionalitäten implementiern 
konnten und es mir ermöglicht haben mich recht schnell einzuarbeiten und mitentwickeln zu können.

Beim nächsten Projekt würde ich als Projektmanager mehr darauf achten dass alle Teammitglieder 
regelmäßig am Projekt arbeiten und ihre Aufgaben auch im geforderten Zeitraum versuchen zu 
erledigen. Außerdem sollten einheitliche "Richtlinien" für den Umgang mit Git und anderen 
genutzten Tools von Anfang an etabliert und auch geprüft werden, da ich festgestellt habe dass 
der richtige Umgang mit Hilfsmitteln wie Git und AsciiDoc bei manchen Teammitgliedern kaum 
bekannt ist. Des Weiteren sollte ich beim nächsten mal mehr darauf achten, dass sich das Projekt 
auch in einem für uns machbaren Rahmen hält. Die Kunden hatten stetig neue Ideen für die 
Software. Auf der einen Seite möchte ich die Entwickler da nicht aufhalten diese 
Funktionalitäten zu implementieren, da die Wetterstation-Software dadurch nur brauchbarer wird. 
Zum anderen wurde es dadurch nicht möglich die Software bis zur Abgabe am 31.07.2020 nach den 
letzten Wünschen der Kunden fertig zu stellen. So wurden z.B. die Diagramme im Adminpanel 2 Tage 
vor Abgabe vom Kunden nochmal umgeworfen, da doch noch andere Daten vom Raspberry gesammelt 
werden. Die neuen Diagramme haben es natürlich nicht in die Übergabeversion geschafft. Dadurch 
ist diese Version für den Kunden allerdings auch nicht praktisch nutzbar. Ich würde dem Kunden 
beim nächsten Projekt daher wahrscheinlich eine Deadline für neue Features geben, damit sich die 
Entwickler nach der Deadline auf die bis dahin geforderten Funktionalitäten konzentrieren können.

Zusammenfassend werte ich das Projekt für mich persönlich als Erfolg. Ich konnte Einblicke in 
das Projekmanagement und die Enwicklerarbeit gewinnen. Durch die "realen" Kunden konnte ich auch 
gut die Entwicklung der Anforderungen durchspielen und konnte teilweise auch erkennen, dass man 
den Kunden manchmal eher vorschlagen sollte was er braucht und nicht immer genau das umsetzten 
sollte was er sich in dem Moment denkt.