= Reflexion Alexander Schoch

=== Teamrolle: Entwickler/ Projektmanager

Innerhalb des Projekts war ich seit Software Engineering I als Entwickler, dabei hauptsächlich für die Entwicklung des Front-Ends zuständig. Rückblickend habe ich gelernt, dass Kommunikation und Arbeitsverteilung ein kritischer Punkt in einem Projekt solchen Ausmaßes sind. So hat sich meine ursprüngliche Zweitrolle als Analyst in Software Engineering I zu einem Ersatzprojektmanager im Falle von Clemens Abwesenheit geändert. Ebenso wurde mir klar, wie wichtig der Einsatz von agilen Methoden im Projektverlauf sind. Viele Anforderungen an das System änderten sich mit dem physischen Bau der Wetterstation. Zum Beispiel sollte die Datenakquise nicht mehr einmal halbstündlich erfolgen, sondern minütlich und einmal halbstündlich an den Server geschickt werden und eine Vielzahl von Messwerten in Bezug auf das Adminpanel änderten sich. Die Umsetzung solch drastischer Änderungen wären im Wasserfallmodell kaum möglich gewesen. Insgesamt hat es mir viel Spaß gemacht an einem Softwaresystem zu arbeiten, von dem man ausgehen kann, das am Ende auch eingesetzt wird und für die Vereinsmitglieder des MFCR einen Mehrwert bietet. Auch wenn innerhalb des Teams nicht alles glatt lief, die angestrebten Ziele einzelner Iterationen nicht immer zum Ende dieser erreicht wurden und die Aufgabenverteilung teilweise sehr unausgeglichen war, sehe ich das Projekt als Erfolg an.

Auch technisch konnte ich viele neue Erfahrungen im Projektverlauf sammeln. Durch Angular konnte ich mich in meiner Rolle mit einer neuen Technologie beschäftigen. Auch wenn das Erlernen einer für mich neuen Programmiersprache viel Zeit in Anspruch genommen hat, habe ich es als eine gute Möglichkeit gesehen mich mit  Webapplikationen tiefer zu beschäftigen und mich als Entwickler zu verbessern.

Besonders positiv möchte ich auch die Kommunikation innerhalb des Teams sowie mit den Kunden hervorheben. Auch wenn die geänderten Umstände aufgrund von Corona für anfängliche Schwierigkeiten sorgte, haben wir uns als Team schnell auf ein wöchentliches und mit dem Kunden auf einen mindestens zweiwöchentliches Meeting einigen können und kontinuierlich beibehalten. So konnten wir uns regelmäßig Feedback von den Kunden einholen, neue Ziele bis zum nächsten Treffen spezifizieren, uns über den Stand der Wetterstation erkundigen und auf Änderungen schneller reagieren. Auch die Einrichtung eines Discord-Servers für die Kommunikation zwischen einzelnen Teammitgliedern wurde gelegentlich genutzt und ermöglichte das gemeinsame Programmieren oder Fehlersuche im Code.

Auch die Arbeitsverteilung unter den Entwicklern und dem Architekt hat sehr gut funktioniert. Die Unterteilung in die zwei großen Bereiche Front-End und Back-End mit ihren jeweils zugeordneten Entwicklern hatte den Vorteil, dass sich die Entwickler wenig in die Quere kamen, Mergekonflikte minimiert und man sich anschließend lediglich um die Zusammenführung kümmern musste.

Im nächsten Projekt würde ich mehr Fokus darauf legen, dass der Kunde die vereinbarte Infrastruktur schnellstmöglich bereitstellt. Ebenso werde ich mehr darauf achten einen festen Featurestopp im Projekt zu definieren. So kann ein größeres Augenmerk auf Tests, Qualitätssicherung und Stabilität des Systems gelegt werden.

Abschließend lässt sich sagen, dass so ein großes Projekt im Verlauf von Software Engineering I und II eine sinnvolle und wichtige Bereicherung war. Nicht nur um die erlernten Vorlesungsinhalte in einen praktischen Kontext zu setzen, sondern auch um die Kommunikation und Organisation eines Teams zu verbessern.