== Reflexion Agustin Calvimontes

=== Teamrolle: Deployment Engineer, Technical Writer
In unserem Projekt der "Wetterstation" habe ich vieles gelernt. Die Entdeckung und Verwendung mehrerer Tools hat Spaß gemacht. Wie zum Beispiel GitHub als unser wichtigstes Tool für die Arbeit am Projekt. Ich bin auch froh mich mit Python und Asciidoc beschäftigt zu haben. Die Arbeit mit den Kommilitonen war auch sehr wertvoll und hilfreich. Ich habe schnell gelernt, dass die Kommunikation im Team sehr bedeutend ist. Der Umgang mit dem Kunden war auch eine gute Erfahrung. Seit Beginn hat es mir gefallen an etwas zu arbeiten, das wirklich von dem Kunden genutzt werden wird. Es hat mir einen großen Einblick gegeben wie die Arbeit im Bereich Software Engineering ausschaut und somit wie der Alltag abläuft. Mit dem Endzustand der Software bin ich aüßerst positiv beeindruckt, denn trotz der Probleme wie der Ausfall von unseren Treffen in Person, haben wir stets Lösungen gefunden und auch dank starkes Projektmanagements haben wir das Projekt abgeschlossen. Schließlich bin ich froh an diesem Projekt teilgenommen zu haben.
