# Generated by Django 3.0.2 on 2020-06-24 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementSession',
            fields=[
                ('session_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('image_size', models.IntegerField(null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.FloatField()),
                ('direction', models.FloatField()),
                ('measure_time', models.DateTimeField()),
                ('measurement_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restapi.MeasurementSession')),
            ],
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degrees', models.FloatField()),
                ('measure_time', models.DateTimeField()),
                ('measurement_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restapi.MeasurementSession')),
            ],
        ),
        migrations.CreateModel(
            name='SolarCell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.FloatField()),
                ('voltage', models.FloatField()),
                ('measure_time', models.DateTimeField()),
                ('measurement_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restapi.MeasurementSession')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/%Y/%m')),
                ('measure_time', models.DateTimeField()),
                ('measurement_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restapi.MeasurementSession')),
            ],
        ),
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.FloatField()),
                ('voltage', models.FloatField()),
                ('temperature', models.FloatField()),
                ('measure_time', models.DateTimeField()),
                ('measurement_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restapi.MeasurementSession')),
            ],
        ),
    ]
