# Generated by Django 3.0.2 on 2020-08-19 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_height', models.IntegerField()),
                ('res_width', models.IntegerField()),
                ('measure_intervall_sensors', models.IntegerField()),
                ('measure_intervall_cam', models.IntegerField()),
                ('post_intervall_sensor_data', models.IntegerField()),
                ('post_intervall_image_data', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementSession',
            fields=[
                ('session_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('image_size', models.IntegerField(null=True)),
                ('time', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('direction', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('measure_time', models.DateTimeField(db_index=True, null=True)),
                ('measurement_session', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restapi.MeasurementSession')),
            ],
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degrees', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('measure_time', models.DateTimeField(db_index=True, null=True)),
                ('measurement_session', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restapi.MeasurementSession')),
            ],
        ),
        migrations.CreateModel(
            name='SolarCell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('voltage', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('measure_time', models.DateTimeField(db_index=True, null=True)),
                ('measurement_session', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restapi.MeasurementSession')),
            ],
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('voltage', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('measure_time', models.DateTimeField(db_index=True, null=True)),
                ('measurement_session', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restapi.MeasurementSession')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/%Y/%m')),
                ('measure_time', models.DateTimeField(db_index=True, null=True)),
                ('measurement_session', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restapi.MeasurementSession')),
            ],
        ),
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=2, null=True)),
                ('measure_time', models.DateTimeField(db_index=True)),
                ('measurement_session', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restapi.MeasurementSession')),
            ],
        ),
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('voltage', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('measure_time', models.DateTimeField(db_index=True)),
                ('measurement_session', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restapi.MeasurementSession')),
            ],
        ),
        migrations.CreateModel(
            name='ConfigSession',
            fields=[
                ('configuration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='restapi.Configuration')),
                ('time', models.TimeField(auto_now_add=True)),
                ('applied', models.BooleanField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
