# Generated by Django 3.0.2 on 2020-07-08 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='measurement_session',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restapi.MeasurementSession'),
        ),
        migrations.AlterField(
            model_name='image',
            name='measurement_session',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restapi.MeasurementSession'),
        ),
        migrations.AlterField(
            model_name='solarcell',
            name='measurement_session',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restapi.MeasurementSession'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='measurement_session',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restapi.MeasurementSession'),
        ),
        migrations.AlterField(
            model_name='wind',
            name='measurement_session',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restapi.MeasurementSession'),
        ),
    ]
