# Generated by Django 3.0.2 on 2020-04-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_auto_20200420_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/% Y/% m/% d/')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
