# Generated by Django 3.0.2 on 2020-08-19 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_auto_20200819_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configsession',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
