# Generated by Django 3.0.2 on 2020-04-22 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='uploaded',
            new_name='time',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/%Y/%m/%d'),
        ),
    ]
