# Generated by Django 3.0.2 on 2020-05-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_auto_20200422_0314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='temperature',
            old_name='value',
            new_name='degrees',
        ),
        migrations.AlterField(
            model_name='image',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='wind',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
