# Generated by Django 3.0.2 on 2020-08-27 00:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
