# Generated by Django 3.0.2 on 2020-08-31 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0005_configuration_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuration',
            old_name='post_intervall_cam_data',
            new_name='post_intervall',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='post_intervall_sensor_data',
        ),
    ]
