# Generated by Django 3.0.2 on 2020-05-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0005_auto_20200514_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.ImageField(upload_to='images/%Y/%m'),
        ),
    ]
