= Arbeitsweise mit Git

== Motivation
Das Git-Repository des Projektes ist wenig gepflegt in dem Sinne, dass Änderungen nur in großen Schritten in den jeweiligen groben Branches gepusht werden und der Master-Branch was den Code angeht mittlerweile sehr veraltet ist.

== Stand jetzt
- Branches werden teilweise von mehreren Personen  gleichzeitig bearbeitet
- Commits werden teilweise in großen Paketen getätigt
- Branches erfahren untereinander keine Zusammenführungen, d.h. dass keine Änderungen von einem Branch bei einem anderen zu finden sind
- Der Master-Branch ist aus Implementierungssicht verwaist

== Angestrebte Arbeitsweise
- Regelmäßige, kleine Commits
- nur lauffähige und ggf. getestete Versionen werden auf den Master-Branch übernommen, dies aber regelmäßig
- spezifische Branches, z.B. Adminpanel-Branch, Galerie-Branch, Graphen-Branch etc.
- Branches laufen nur über kurze Distanzen neben Master

== Maßnahmen
- Arbeit mit Git vertiefen, z.B. anhand des SE-Prakikums link:http://www.informatik.htw-dresden.de/~zirkelba/praktika/se/arbeiten-mit-git-und-asciidoc/praktikumsaufgaben-teil-4.html[]
- Branches auf den aktuellen Stand bringen und mit dem Master zusammenführen, sodass auf dem Master-Branch eine aktuelle, lauffähige Version zu finden ist
- Grobe Branches durch kleinteilige ersetzen