== Iterationsplan 22.04.2020 - 06.05.2020

=== Priorisierte Aufgaben
- Front-End mit grundsätzlichen Funktionen ausstatten -> Alex
- Front-End und Back-End zusammenführen -> Alex, Philipp, Justin
- Datenformat der Wetterdaten festlegen -> Alex, Philipp, Justin
- Rest-API vervollständigen, Authentifizierung regeln -> Philipp
- Dokumentation überarbeiten -> Josefin
- Aufgaben des Technical Writer/Deployment Engineer auf das Projekt abbilden -> Agustin
- Test auf Grundlage von Use-Cases beschreiben und entwickeln -> Hannes
- Projektabgabe spezifizieren (welche Dokumente nötig etc.) -> Clemens

=== Risiken
Risiken der Anforderungsanalyse und Planung identifizieren, analysieren, bewerten und Gegenmaßnahmen planen 

include::Risk_List.adoc[]

=== Bewertung
Das Front-End wurde mit Grundfunktionalitäten ausgestattet, lediglich die Bildergalerie fehlt.
Das Back-End und das Front-End sind soweit zusammengeführt, dass eine Kommunikation dazwischen möglich ist.
Das Datenformat der Wetterdaten wurde uns vom Kunden noch nicht vorgelegt.
Die Rest-API wurde ausgebaut, allerdings ist die Implementierung einer Authentifizierung in der Priorität nach hinten gerückt.
Die Überarbeitung der Dokumentation wurde angefangen.
Ein Testdokument wurde erstelt, bei welchem die Grundsätze des Testens für die Wetterstation aufgeschrieben wurden.
DIe Projektabgabe wurde nicht weiter spezifiziert.
