== Iterationsplan 23.01.2020 - 06.02.2020

=== Priorisierte Aufgaben
- Überarbeiten der
    * Use Cases
    * Wireframes
    * System Wide Requirements
    * Vision
auf Basis der neuen Erkenntnisse aus dem Kundengespräch
- Design-Dokument erstellen
- Belegabgabe vorbereiten/durchführen
- Git-Repo säubern und Git-Projekt überarbeiten

=== Work Items List
https://docs.google.com/spreadsheets/d/1HxpITdcoMaGQRV4cEODZcJ2ZDh8JpjwfIRo5Z4ReBgc/edit?usp=sharing

=== Risiken
Risiken der Anforderungsanalyse und Planung identifizieren, analysieren, bewerten und Gegenmaßnahmen planen 

include::Risk_List.adoc[]

=== Bewertung
Die Bewertung der Iteration erfolgt beim Teamtreffen nach der Iteration anhand der Verständlichkeit der Aufgabenlösung gegenüber anderen Teammitgliedern und dem Aufkommen an neuen Fragen für das nächste Kundengespräch, wobei mehr Fragen eine bessere Lösung der Aufgaben andeuten können. Die Use Cases sollten nun mit den Anforderungen der Kunden übereinstimmen (und vor allem widerspruchsfrei sein). Die Wireframes sollten diesen Anforderngen ebenfalls entsprechen.