= Projektorganisation
Autoren: Josefin Hähne

== Team

Unser Team besteht aus 7 Mitgliedern: Clemens Kujus, Alexander Schoch, Philipp Barth, Justin Schirdewahn, Agustin Calvimontes, Josefin Hähne und Hannes Fogut, welcher erst im vierten Semster in unser Team kam, da Martin Großmann unser Team nach SE1 verlassen hat. 

== Rollen

Jedem von uns sind 2 Rollen zugeteilt, einmal die Hauptrolle und meist noch ein Backup. 
Clemens Kujus übernahm nach einem Tausch mit Martin Großmann die Rolle als Projektmanager und Analyst, Alexander Schoch ist Entwickler und Projektmanager, Philipp Barth Architekt und Entwickler, Justin Schirdewahn Entwickler und Tester, Agustin Calvimontes Deployment Engineer und Technical Writer, Josefin Hähne Analyst und Architekt und Martin Großmann beziehungsweise in SE2 Hannes Fogut Tester und Entwickler, da Martin Großmann unser Team verlassen hat.

Jedoch haben wir im Laufe des Projekts nicht mehr an der strikten Rollenverteilung festgehalten, da die Arbeit sonst sehr unausgeglichen gewesen wäre.

== Kommuniktion

=== im Team
Im Team findet die Kommunikation über WhatsApp für kleine und schnelle Absprachen statt. Wir haben regelmäßige Teamtreffen, sowohl an der HTW als auch online und alltäglichen Kontakt in Vorlesungen und Übungen/Praktika an der HTW (enfällt in SE2 aufgrund einer Pandemie).
Für die Themenbearbeitung und Aufgabenverteilung nutzen wir die in GitHub vorgesehenen Issues. 

=== zum Auftraggeber
//Email
//Treffen
== eingesetzte Tools

= eingesetzte Techniken und Praktiken